services:
  mysql:
    image: mysql:8
    container_name: mysql-restos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: restos_collectes
      MYSQL_USER: restos_user
      MYSQL_PASSWORD: restos_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-restos
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: restos_user
      PMA_PASSWORD: restos_pass
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: